# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='expense date')),
                ('particular', models.CharField(max_length=100)),
                ('tds', models.FloatField(default=0.0)),
                ('tpn', models.CharField(max_length=50)),
                ('paid_for_service', models.FloatField(default=0.0)),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=10)),
                ('passport', models.CharField(max_length=50)),
                ('permit_visa', models.CharField(max_length=50)),
                ('passport_link', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Guestcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=50)),
                ('idcardnumber', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('guide_license', models.CharField(max_length=50)),
                ('driver_license', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tourgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('no_adults', models.IntegerField(default=0)),
                ('no_children_below15', models.IntegerField(default=0)),
                ('no_children_below5', models.IntegerField(default=0)),
                ('entry_date', models.DateField(verbose_name='entry date')),
                ('exit_date', models.DateField(verbose_name='exit date')),
                ('itinerary_link', models.CharField(max_length=250)),
                ('total_package_cost', models.FloatField(default=0.0)),
                ('total_expense_assumed', models.FloatField(default=0.0)),
                ('total_final_expense_incurred', models.FloatField(default=0.0)),
                ('focal_person', models.CharField(max_length=50)),
                ('focal_person_number', models.CharField(max_length=50)),
                ('vehicle_no', models.CharField(max_length=10)),
                ('vehicle_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TourgroupPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.People')),
                ('tourgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tourgroup')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='Guestcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Guestcategory'),
        ),
        migrations.AddField(
            model_name='guest',
            name='tourgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tourgroup'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tourgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tourgroup'),
        ),
    ]
